version: "3.9"
services:
  servidor:
    container_name: Apis
    restart: always
    build: ./
    ports:
      - "9000:3000"
    volumes:
      - ./src:/usr/src/app/src:rw
    environment:
      - PORT=3000
      - AES_KEY=inmovili-todounmundoinmobiliario
      - JWT_SECRET=products-api
      - JWT_EXPIRES=1800
      - NODE_ENV=production
      - DB_NAME=services
      - DB_USER=root
      - DB_PWD=C0l0mb1@
      - DB_HOST=144.126.212.222
      - DB_PORT=3306
      - DB_DIALECT=mysql
      - DB_LOGS=false
      - ESLINT_NO_DEV_ERRORS=true
      - MONGODB_URI=mongodb://localhost/apicompany
      - FRISTNAME=Raul
      - LASTNAME=Saldarriaga
      - USERNAME=RaulAdmin
      - EMAIL=raul@gmail.com
      - PASSWORD=colombia
      - DOCUMET=1082926704
      - PHONE=573004880579
      - NAME=GrupoElite
      - ALIAS=GE
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_AUTH_USER=inmovily@gmail.com
      - SMTP_AUTH_PASS=wnqacvhxuzdfhcpq
